import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import LandingPage from '@/components/LandingPage'
import FoodSection from '@/components/FoodSection'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Angan Sweets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <LandingPage />
      <FoodSection />
      <div className="footer">
        <div className="logo">
            <Image src='/img/logo.png' alt='logo' width={100} height={50}/>
        </div>
        <div className="footer-items">
            <li>Menu</li>
            <li>Privacy Policy</li>
            <li>Help Center</li>
        </div>
    </div>
    </>
  )
}
