import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import LandingPage from '@/components/LandingPage'
import FoodSection from '@/components/FoodSection'
import SelectSearch from 'react-select-search'
import { searchData } from '../../data'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Angan Sweets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  )
}
